- name: Create user with encrypted password and encrypted playbook
  hosts: clients
  remote_user: root 
  vars_files:
    - secret.yaml

  tasks: 
  - name: Create user with encrypted password
    user:
      name: user30
      password: "{{ secret | password_hash('sha512') }}"
      state: present