- name: Create user with encrypted password
  hosts: clients
  remote_user: root 
  vars:
    secret: Secure123

  tasks: 
  - name: Create user with encrypted password
    user:
      name: user20
      password: "{{ secret | password_hash('sha512') }}"
      state: present